spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/phoneshop
    username: admin
    password: brawitadmin95
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
logging:
  level:
    liquibase: DEBUG
